---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rtorrent-data-pv
  namespace: default
spec:
  capacity:
    storage: 6T
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/torrents
    server: shannara
    readOnly: false
