---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rtorrent-config-pv
  namespace: default
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/torrents/servers
    server: shannara
    readOnly: false
